### ISSUE TITLE
Add highlight support for TODO: or FIXME: etc.

### ISSUE THREAD

**Issue by sky124380729** [vuejs/vitepress#1797]
### Is your feature request related to a problem? Please describe.

Add highlight support for TODO: or FIXME: etc.

Just like vscode extention [TODO Highlight]

Here is the IDE effect：

![image](https://user-images.githubusercontent.com/23203328/212520705-7b5715a5-e54e-440f-851b-ea0dff855957.png)

### Describe the solution you'd like

'''js
// TODO: To be realized in the future  [!code todo]
const test = () => null
'''

similar with `[!code  focus]` or `[!code  hl]`

### Describe alternatives you've considered

No need for manual controls

When parsing the language template in markdown, it is found that strings such as `TODO:` or `FIXME:` are automatically highlighted

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Feel free to create a PR at https://github.com/innocenzi/shiki-processor.
