### ISSUE TITLE
TODO list todo is not supported

### ISSUE THREAD

**Issue by LetTTGACO** [vuejs/vitepress#1923]
### Describe the bug

vitepress not support TODO

when i use `- [ ]` in markdown, it wasn't rendered correctly, it's recognized as a list,  just like this:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/37357188/218241878-e9fbec7c-9848-4166-80fe-8370421d8ce6.png">

It should be identified as
![image](https://user-images.githubusercontent.com/37357188/218241987-1010d16e-b95f-484e-b949-c5ebc6bd7072.png)

### Reproduction

just like this

- [x] TODO-1
- [x] TODO-2
- [ ] TODO-1

but in vitpress
![image](https://user-images.githubusercontent.com/37357188/218242214-6936160f-4417-4841-803b-7c1efa85d210.png)

### Expected behavior

just like on github

- [x] TODO-1
- [x] TODO-2
- [ ] TODO-1

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 87.81 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Edge: 97.0.1072.62
    Firefox: 77.0.1
    Safari: 16.3
  npmPackages:
    vitepress: 1.0.0-alpha.45 => 1.0.0-alpha.45
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
We had this FR back in 2021 too (#413) but we didn't saw any demand there for about an year. Third-party markdown-it plugins work great FWICT. We probably should add some common ones to docs if someone wants. I still think that there isn't any need to add them to the core.
