### ISSUE TITLE
If the "import.meta.env" string appears in config, an error will be reported when building

### ISSUE THREAD

**Issue by Xaviw** [vuejs/vitepress#2108]
### Describe the bug

```
⠇ building client + server bundles...Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /@siteData:15:106
13:   }
14: }
15:         export default deserializeFunctions(JSON.parse("{\"lang\":\"en-US\",\"dir\":\"ltr\",\"title\":\"import.meta.e...
                                                                                                              ^
✖ building client + server bundles...
build error:
RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (file:///D:/project/vitepress-test/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at Module.error (file:///D:/project/vitepress-test/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:13316:16)
    at Module.tryParse (file:///D:/project/vitepress-test/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:13993:25)
    at Module.setSource (file:///D:/project/vitepress-test/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:13603:39)
    at ModuleLoader.addModuleSource (file:///D:/project/vitepress-test/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:23569:20)
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

Set the value of any attribute in config to "import.meta.env",such as this

```js
export default {
  title: "import.meta.env"
}
```

### Expected behavior

should build successfully

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13400F
    Memory: 7.69 GB / 15.81 GB
  Binaries:
    Node: 18.14.1 - ~\AppData\Local\Volta\tools\image\node\18.14.1\node.EXE
    Yarn: 4.0.0-rc.39 - ~\AppData\Local\Volta\tools\image\yarn\4.0.0-rc.39\bin\yarn.CMD
    npm: 9.3.1 - ~\AppData\Local\Volta\tools\image\node\18.14.1\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.41)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It's not exactly a bug, vite replaces certain terms. As a workaround, IG you can use something like `i\0mport.meta.env`

**Comment by Xaviw** [comment]
> It's not exactly a bug, vite replaces certain terms. As a workaround, IG you can use something like `i\0mport.meta.env`

I noticed that some HTML tag text is also misrecognized. Can you tell me which characters should be avoided in config, Or in which part of the source code can I find the answer

**Comment by brc-dd** [comment]
Nothing except import.meta/process.env/defines should be an issue. Can you tell in particular what's breaking?

**Comment by Xaviw** [comment]
> Nothing except import.meta/process.env/defines should be an issue. Can you tell in particular what's breaking?

I think it should be my mistake when I use `useData`, thank you for answering
