### ISSUE TITLE
Not Rendering markdown checklist

### ISSUE THREAD

**Issue by EmptyBox-Design** [vuejs/vitepress#413]
### Describe the bug

I wrote a markdown checklist using the following syntax and is rendered as an unordered list rather than a checklist.

`index,md`

```
- [ ] Mercury
- [ ] Saturn
- [ ] Earth
- [ ] Mars
```

What is rendered

<img width="274" alt="Screen Shot 2021-10-11 at 8 46 06 PM" src="https://user-images.githubusercontent.com/27181419/136872493-20cc4a0c-a1ac-4cdf-ac20-e6952f8f4819.png">

### Reproduction

Created basic project based on the steps on the [Getting Started](https://vitepress.vuejs.org/guide/getting-started.html).

### Expected behavior

- [ ] Mercury
- [ ] Saturn
- [ ] Earth
- [ ] Mars

### System Info

```shell
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.18 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Safari: 14.0.3
  npmPackages:
    vitepress: ^0.20.0 => 0.20.0
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
This is not supported I think. I don't think it does in VuePress either? I might be wrong. It might be interesting to have it, but is it worth it? I mean what should happen if user checks the checkbox? Do we want to store the checked state and save it to the local storage? What is the point of having checklist rendered?

**Comment by posva** [comment]
That is a GitHub markdown flavored feature and since docs are not editable, it doesn't really make sense in docs.
That being said it could be supported with a markdown-it plugin

**Comment by brc-dd** [comment]
Refer this: https://vitepress.vuejs.org/guide/markdown.html#advanced-configuration

You can use any third party plugin - https://www.npmjs.com/search?q=keywords%3Amarkdown-it-plugin%20checkbox

**Comment by kiaking** [comment]
Closing for now. I also agree this doesn't need be implemented in VitePress core. But if we get high demand for it, we could reconsider it in the future 👍

**Comment by thedamon** [comment]
In terms of documenting software this is an awesome thing to have in core I think, but... as you say not hard to implement.
