### ISSUE TITLE
add meta to markdown-it env

### ISSUE THREAD

**Issue by kagawagao** [vuejs/vitepress#444]
### Is your feature request related to a problem? Please describe.

there is no context info currently, such as `filepath`/`vite compiler`, when `markdown-it` parse markdown files, and this leads to the inability to resolve relative file path when parsing markdown files, or add dependency to compiler to make hmr work as expected

for example, `snippet`

https://github.com/vuejs/vitepress/blob/ea6cb00c3e9099d45fc236bff0f7c42a65d558dc/src/node/markdown/plugins/snippet.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L145-L147

```js
// loader always undefined
if (loader) {
  loader.addDependency(src)
}
```

### Describe the solution you'd like

add meta to [`markdown-it`](https://markdown-it.github.io/markdown-it/#MarkdownIt.render) be called) when [`render`](https://github.com/vuejs/vitepress/blob/ea6cb00c3e9099d45fc236bff0f7c42a65d558dc/src/node/markdown/markdown.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L96-L105)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
#869 will add file path in `env`. Will track that loader thing in #117.
