### ISSUE TITLE
Make import.meta work in .vitepress/config.js

### ISSUE THREAD

**Issue by kinoli** [vuejs/vitepress#572]
### Describe the bug

Trying to use `const articles = import.meta.glob('../*.js')` within config.js will give you an error.

```
failed to load config from /**/docs/.vitepress/config.js
```

### Reproduction

add `const articles = import.meta.glob('../*.js')` to config.js

### Expected behavior

It would be nice to be able to build a dynamic sidebar based on files you load from a directory.

### System Info

```shell
osx, new build of vitepress as of today
```

### Additional context

Since, `require("fs");` and `require("path")` dont work with vite, how else might I analyze the file system to build my sidebar?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
Might be nice to have. At the moment, you could create pure script file that reads all dir and output JSON file or something to some directly, and then import that file in config.

Then run that script before VirePress build command.

```json
  "scripts": {
    "build": "node buildDir.js && vitepress build"
  }
```

**Comment by brc-dd** [comment]
I am easily able to do stuff like this inside config file:

```js
import fg from 'fast-glob'
import matter from 'gray-matter'

const files = fg.sync(['**/*.md', '!**/node_modules'])
files.forEach((file) => {
  const { data } = matter.read(file)
  console.log(data.title)
})

export default {...}
```

I don't think we need to support `import.meta.glob`.
